name: SendbirdAuthSDK

options:
  bundleIdPrefix: com.sendbird
  deploymentTarget:
    iOS: "13.0"
    macOS: "11.0"

settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  SWIFT_VERSION: "5.9"
  BUILD_LIBRARY_FOR_DISTRIBUTION: YES
  DEFINES_MODULE: YES

targets:
  SendbirdAuthSDK:
    type: framework
    platform: [iOS, macOS]
    sources:
      - Sources/SendbirdAuth
    info:
      path: Sources/SendbirdAuth/Info.plist
    settings:
      PRODUCT_NAME: SendbirdAuthSDK
      PRODUCT_BUNDLE_IDENTIFIER: com.sendbird.SendbirdAuthSDK
