//
//  BaseStatRuntimeIdTests.swift
//  SendbirdAuthTests
//
//  Created by Tez Park on 2025/01/23.
//

import XCTest
@testable @_spi(SendbirdInternal) import SendbirdAuthSDK

final class BaseStatRuntimeIdTests: XCTestCase {

    // MARK: - Global RuntimeId Tests

    func test_globalRuntimeId_shouldBeAutoGenerated() throws {
        // globalRuntimeId는 자동 생성되어 있어야 함
        XCTAssertFalse(BaseStat.globalRuntimeId.isEmpty)
    }

    func test_globalRuntimeId_shouldBePersistent() throws {
        // 동일한 값이 유지되어야 함
        let firstAccess = BaseStat.globalRuntimeId
        let secondAccess = BaseStat.globalRuntimeId
        XCTAssertEqual(firstAccess, secondAccess)
    }

    // MARK: - includeRuntimeId Tests

    func test_baseStat_includeRuntimeId_true_shouldSetGlobalRuntimeId() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            includeRuntimeId: true
        )
        XCTAssertEqual(stat.runtimeId, BaseStat.globalRuntimeId)
    }

    func test_baseStat_includeRuntimeId_false_shouldBeNil() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            includeRuntimeId: false
        )
        XCTAssertNil(stat.runtimeId)
    }

    func test_baseStat_default_includeRuntimeId_shouldBeNil() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234
        )
        XCTAssertNil(stat.runtimeId)
    }

    // MARK: - Property Access Tests

    func test_baseStat_runtimeId_canBeSet() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234
        )
        XCTAssertNil(stat.runtimeId)

        let runtimeId = UUID().uuidString
        stat.runtimeId = runtimeId
        XCTAssertEqual(stat.runtimeId, runtimeId)
    }

    // MARK: - AI Agent Stats Type Tests

    func test_baseStat_aiAgentStats_shouldHaveCorrectStatType() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234
        )
        XCTAssertEqual(stat.statType, .aiAgentStats)
        XCTAssertEqual(stat.statType.rawValue, "ai_agent:stats")
    }

    func test_baseStat_withData_shouldSetCorrectly() throws {
        let data: [String: AnyCodable] = [
            "key": AnyCodable("conversation_initial_render"),
            "conversation_id": AnyCodable("conv_123")
        ]
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            data: data
        )

        XCTAssertNotNil(stat.data)
        XCTAssertEqual(stat.data?["key"]?.value as? String, "conversation_initial_render")
        XCTAssertEqual(stat.data?["conversation_id"]?.value as? String, "conv_123")
    }

    // MARK: - Encoding Tests

    func test_baseStat_encode_withIncludeRuntimeId_shouldIncludeInJSON() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            data: ["key": AnyCodable("value")],
            includeRuntimeId: true
        )

        let encodedValue = try JSONEncoder().encode(stat)
        let dictResult = try JSONSerialization.jsonObject(with: encodedValue) as? [String: Any]

        XCTAssertEqual(dictResult?["runtime_id"] as? String, BaseStat.globalRuntimeId)
        XCTAssertEqual(dictResult?["ts"] as? Int, 1234)
        XCTAssertEqual(dictResult?["stat_type"] as? String, "ai_agent:stats")
    }

    func test_baseStat_encode_withoutIncludeRuntimeId_shouldNotIncludeInJSON() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234
        )

        let encodedValue = try JSONEncoder().encode(stat)
        let dictResult = try JSONSerialization.jsonObject(with: encodedValue) as? [String: Any]

        XCTAssertNil(dictResult?["runtime_id"])
    }

    // MARK: - Decoding Tests

    func test_baseStat_decode_withRuntimeId_shouldSetCorrectly() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            includeRuntimeId: true
        )

        let encodedValue = try JSONEncoder().encode(stat)
        let result = try JSONDecoder().decode(BaseStat.self, from: encodedValue)

        XCTAssertEqual(result.runtimeId, BaseStat.globalRuntimeId)
        XCTAssertEqual(result.timestamp, 1234)
        XCTAssertEqual(result.statType, .aiAgentStats)
    }

    func test_baseStat_decode_withoutRuntimeId_shouldBeNil() throws {
        let stat = BaseStat(
            statType: .aiAgentStats,
            timestamp: 1234,
            includeRuntimeId: false
        )

        let encodedValue = try JSONEncoder().encode(stat)
        let result = try JSONDecoder().decode(BaseStat.self, from: encodedValue)

        XCTAssertNil(result.runtimeId)
    }
}
